Add the ability to set a default translator and text domain
zendframework/zend-i18n pull request #60
Opened 2016-10-18 15:20 UTC by MatthiasKuehneEllerhold

Discussed in https://github.com/zendframework/zend-form/pull/115:

Ive added the ability to set a default translator and text domain to avoid having to set them  to every View-Helper.
Because I've wanted to change the text domain of every view helper and right now I have to instantiate every view helper to set it. This would reduce the overhead necessary and increase the runtime performance.
Another possibility would be an initializer that sets the appropriate translator and domain upon instantiation of a view helper.

Any thoughts on this?

2016-10-20 12:24 UTC, MatthiasKuehneEllerhold commented
@adamlundrigan Ive added the tests.

2016-12-05 13:29 UTC, Ocramius requested changes
This doesn't seem like a good idea to me. Instead, we should probably inject the default translator via helper plugin manager, and avoid staticness at all costs for these purposes.

From my PoV, this is a 👎

2016-12-05 13:29 UTC, Ocramius commented on src/View/Helper/AbstractTranslatorHelper.php
> +    protected $translatorTextDomain = null;
This is a slight BC Break - needs to be documented, plus I really wouldn't do it, unless strictly needed

2016-12-05 13:29 UTC, Ocramius commented on src/View/Helper/AbstractTranslatorHelper.php
> +    protected static $defaultTranslator;
Why add them as static? Also, why protected?

2016-12-05 13:29 UTC, Ocramius commented on src/View/Helper/AbstractTranslatorHelper.php
> +    protected static $defaultTranslatorTextDomain = 'default';
Same question

2016-12-05 13:29 UTC, Ocramius commented on src/View/Helper/AbstractTranslatorHelper.php
> +            $this->translator = self::getDefaultTranslator();
This looks like hacky DI to me

2016-12-05 13:33 UTC, MatthiasKuehneEllerhold commented on src/View/Helper/AbstractTranslatorHelper.php
> +    protected $translatorTextDomain = null;
Mh, the BC break would only be of some subclass overwrote the standard textDomain with "default" again and expecting the new behavior.
Or am I missing something?

2016-12-05 13:35 UTC, MatthiasKuehneEllerhold commented
@Ocramius Thanks for your review. 
As I said in the description this is a straight up copy of zend-validator (with some small tweaks).
Using proper DI would be better indeed.

2016-12-05 13:43 UTC, Ocramius commented on src/View/Helper/AbstractTranslatorHelper.php
> +    protected $translatorTextDomain = null;
Yes, but being this a class designed for inheritance, it makes the BC break very noticeable

2017-01-27 14:45 UTC, MatthiasKuehneEllerhold commented
I had some time to review the requested changes and I'm not sure how to proceed.
Seems like `zend-view` injects the MvcTranslator into every view-helper in the `\Zend\View\HelperPluginManager::injectTranslator()` method that implements the `TranslatorAwareInterface` but I dont have a clue how to add a configurable text domain for each view helper in there.

I'm gonna close this PR because atm I'm unable to proceed with it.

2017-01-27 14:45 UTC, closed without merging