Add getCacheId() and clearCache() method to Translator
zendframework/zend-i18n pull request #93
Opened 2018-04-26 08:15 UTC by MatthiasKuehneEllerhold

See https://github.com/zendframework/zend-i18n/pull/63 for discussion.

2018-04-27 19:37 UTC, malukenho requested changes
I’m missing tests for the introduced api

2018-04-27 19:37 UTC, malukenho commented on src/Translator/Translator.php
> +     * @param    string $locale
Too much space

2018-04-27 19:37 UTC, malukenho commented on src/Translator/Translator.php
> +     * @param $locale
Parameter types?

2018-04-30 05:40 UTC, MatthiasKuehneEllerhold commented
Fixes the comments and added tests.

Is there any consensus in the ZF code style about using static methods via `$this` ? (See Unit-Tests `$this->assertXY`...

2018-05-16 16:29 UTC, weierophinney commented
> Is there any consensus in the ZF code style about using static methods via $this ?

For unit tests, that's the style we've consistently done since, well, we began. There's an [open discussion in our forums covering exactly this](https://discourse.zendframework.com/t/this-assert-vs-self-assert/448), though with no consensus as of yet.

2018-05-16 16:37 UTC, weierophinney commented
Thanks, @MatthiasKuehneEllerhold. Merged to develop for release with 2.9.0.

2018-05-16 16:37 UTC, closed without merging